### ISSUE TITLE
Error enabling the plugin

### ISSUE THREAD

**Issue by Eufranio** [caoli5288/xKit#1]
```
java.lang.NoClassDefFoundError: Could not initialize class com.avaje.ebean.EbeanServerFact        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:172) ~[simple        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:177) ~[simple        at com.mengcraft.xkit.Main.onEnable(Main.java:42) ~[xkit-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377) [PlugMan.jar:?        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [Plu        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [Simple        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.ja        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.ja        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.jav        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [Mi        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftSe        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

Happens when the server is starting and when i reload the plugin. When i type /xkit, nothing happens.

**Comment by caoli5288** [comment]
Do not use plugman

**Comment by Eufranio** [comment]
Same happens when the server is starting (loading the plugin naturally).

**Comment by caoli5288** [comment]
Try use newest simpleorm-0.3.3.

**Comment by Eufranio** [comment]
Same: 

```
java.lang.NoClassDefFoundError: Could not initialize class com.avaje.ebean.EbeanServerFactory
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:172) ~[simpleorm-0.3.3.jar:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:177) ~[simpleorm-0.3.3.jar:?]
        at com.mengcraft.xkit.Main.onEnable(Main.java:42) ~[xkit-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:363) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:316) [PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:377) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [PluginCommand.class:1.7.10-1614.57]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) [SimpleCommandMap.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) [CraftServer.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:720) [CraftServer.class:1.7.10-1614.57]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:474) [lt.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by Eufranio** [comment]
Using SimpleORM 0.3.3 from here: **https://github.com/caoli5288/SimpleORM/releases**

**Comment by caoli5288** [comment]
Which server you use? thermos?

**Comment by Eufranio** [comment]
Yes, Thermos B57.

**Comment by caoli5288** [comment]
I think this is thermos' bukkit compatible issue. You log shown could not initialize class `com.avaje.ebean.EbeanServerFactory` which is part of bukkit database support.

**Comment by Eufranio** [comment]
Should I report to them?

**Comment by Eufranio** [comment]
Welp

**Comment by Eufranio** [comment]
Still not working.

**Comment by caoli5288** [comment]
Yes. It's not my plugin's issues because it is a bukkit/spigot plugin.  
You issues is thermos'.
Close if not more information.
