### ISSUE TITLE
An Error with depend

### ISSUE THREAD

**Issue by YuKanJiu** [caoli5288/xKit#12]
https://paste.ubuntu.com/p/XPZCgTXsSd/

**Comment by caoli5288** [comment]
Use latest simpleorm please.

**Comment by YuKanJiu** [comment]
sure.I used simpleorm on the https://www.spigotmc.org/resources/simpleorm.57992/
This was the lastest one.

**Comment by Healthable** [comment]
Already solved.I used 1.4 Simpleorm,Thanks.

**Comment by YuKanJiu** [comment]
I used the lastest but i find other ERROR
[13:31:21] [Server thread/ERROR] [Minecraft]: Error occurred while enabling xKit v1.3-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: Lcom/avaje/ebean/EbeanServer;
	at java.lang.Class.getDeclaredFields0(Native Method) ~[?:1.8.0_241]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583) ~[?:1.8.0_241]
	at java.lang.Class.getDeclaredField(Class.java:2068) ~[?:1.8.0_241]
	at catserver.server.remapper.target.ReflectionMethods.getDeclaredField(ReflectionMethods.java:55) ~[ReflectionMethods.class:git-CatServer-1.12.2-11c12cd]
	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:30) ~[?:?]
	at com.mengcraft.simpleorm.lib.Reflector.lambda$getFieldRef$1(Reflector.java:58) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_241]
	at com.mengcraft.simpleorm.lib.Reflector.getFieldRef(Reflector.java:58) ~[?:?]
	at com.mengcraft.simpleorm.lib.Reflector.getField(Reflector.java:96) ~[?:?]
	at com.mengcraft.simpleorm.Reflect.getLoader(Reflect.java:52) ~[?:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:265) ~[?:?]
	at com.mengcraft.xkit.Main.onEnable(Main.java:46) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-11c12cd]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:594) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[PluginClassLoader.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-11c12cd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	... 21 more
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[PluginClassLoader.class:git-CatServer-1.12.2-11c12cd]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-11c12cd]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_241]
	... 21 more

**Comment by caoli5288** [comment]
I haven't released a new version on spigotmc for a long time. Maybe you need to compile simpleorm from https://github.com/caoli5288/SimpleORM.

**Comment by caoli5288** [comment]
Close for no more informations
